### ISSUE TITLE
Can we use https:// for downloads?

### ISSUE THREAD

**Issue by NickCraver** [KennethB/Chocolatey-Packages#12]
Is there a reason the current `download.microsoft.com` links are not using `https://`? I wanted to ask if there was motivation for the current state before making a PR changing anything. Thanks!

**Comment by KennethB** [comment]
No it wasn't intentional when I originally copied the link from Microsoft it didn't use https.  If the secure link works it can be used, and will help ensure the source is indeed Microsoft.

**Comment by NickCraver** [comment]
Thanks @KennethB, posted #13 to close this out. I appreciate the quick reply :)
