### ISSUE TITLE
default admin file out of date for VS2015 enterprise update 2?

### ISSUE THREAD

**Issue by neutmute** [KennethB/Chocolatey-Packages#2]
Hello - I was just having a look at how the package automation works and it appears the default admin file is out of date for update 2

[$\VisualStudio2015Enterprise\Tools\AdminDeployment.xml](https://github.com/KennethB/Chocolatey-Packages/blob/master/VisualStudio2015Enterprise/Tools/AdminDeployment.xml)

Here is a sample diff - some id's have changed which would affect the results I would think - eg `MicroUpdateV1.2` => `MicroUpdateV2.2`

![2016-04-21_202407](https://cloud.githubusercontent.com/assets/1303131/14705872/f4e8609c-07fe-11e6-95c4-dcbf7b8667da.png)

Happy to PR an update if you agree it needs updating.
How are versions handled? Should I bump it to `14.0.25123.01`

I'm new to chocolatey but tracking the choco package exactly to the version of the app seems difficult when dealing with patches for the package itself.
Perhaps a better strategy might be `14.2.0.1` indicating v`14` of visual studio, update `2` chocolatey package version `1`. Just a suggestion.

**Comment by neutmute** [comment]
any thoughts @KennethB ?

**Comment by KennethB** [comment]
Sorry been swamped at work.

I've been pulling the version from the app to log the build but should probably put a .01 at the end to handle updates to the package.

But proposed is a simpler approach to keeping it all straight.

Makes sense lets do it.

BTW if you want I can add you as a maintainer to the packages.

**Comment by neutmute** [comment]
No worries. Happy to help out and be co maintainer. 

btw - I'm assuming you are happy with the update to `adminDeployment.xml`?

**Comment by neutmute** [comment]
@KennethB - happy to be co maintainer. Lets not let this repo wither!
